# Generated by Django 5.2.11 on 2026-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employment_status",
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="passport",
            field=models.ImageField(blank=True, null=True, upload_to="passports/"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_joined",
            field=models.DateField(auto_now_add=True),
        ),
    ]
