# Generated by Django 5.2.11 on 2026-02-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_employee_employment_status_employee_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_roles",
                        to="api.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="job_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="api.jobrole",
            ),
        ),
        migrations.CreateModel(
            name="RoleKPITemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("target_description", models.TextField(blank=True, null=True)),
                (
                    "job_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_templates",
                        to="api.jobrole",
                    ),
                ),
                (
                    "kpi_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.kpidefinition",
                    ),
                ),
            ],
            options={
                "unique_together": {("job_role", "kpi_definition")},
            },
        ),
    ]
