# Generated by Django 5.2.11 on 2026-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_employeekpi_kpi_definition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrole",
            name="shift_end",
            field=models.TimeField(
                blank=True, help_text="Standard check-out time", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobrole",
            name="shift_start",
            field=models.TimeField(
                blank=True, help_text="Standard check-in time", null=True
            ),
        ),
        migrations.AddField(
            model_name="jobrole",
            name="work_days_type",
            field=models.CharField(
                choices=[
                    ("MON_FRI", "Monday-Friday"),
                    ("DAILY", "Daily (Mon-Sun)"),
                    ("SHIFT_4_4", "4 Days On, 4 Days Off"),
                ],
                default="MON_FRI",
                max_length=20,
            ),
        ),
    ]
