# Generated by Django 5.2.11 on 2026-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_jobrole_shift_end_jobrole_shift_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="late_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="total_late_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
