# Generated by Django 5.2.11 on 2026-02-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_salary_payroll_enhancements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendanceupload",
            old_name="timestamp",
            new_name="uploaded_at",
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_logs",
                to="api.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendancemonthlysummary",
            name="absent_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="api.branch",
            ),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="status",
            field=models.CharField(default="PRESENT", max_length=20),
        ),
        migrations.AlterField(
            model_name="attendanceupload",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to="api.branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendanceupload",
            name="file_path",
            field=models.FileField(default="pending", upload_to="attendance_uploads/"),
            preserve_default=False,
        ),
    ]
