# Generated by Django 5.2.11 on 2026-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_timestamp_attendanceupload_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancemonthlysummary",
            name="absent_deduction_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
