# Generated by Django 5.2.11 on 2026-02-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_attendancemonthlysummary_absent_deduction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancelog",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="api.attendanceupload",
            ),
        ),
    ]
