# Generated by Django 5.2.11 on 2026-02-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_attendancelog_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrecord",
            name="nhf_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="pension_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
