# Generated by Django 5.2.11 on 2026-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_expensecategory_leavetype_employeekpi_is_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("MANAGER", "Manager"),
                    ("STAFF", "Staff"),
                ],
                default="STAFF",
                max_length=10,
            ),
        ),
    ]
