# Generated by Django 5.2.11 on 2026-02-24 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_update_branches_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="reimbursed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="reimbursed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reimbursed_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administration (Superadmin)"),
                    ("HR", "Management (HR)"),
                    ("MANAGER", "Management"),
                    ("ACCOUNTANT", "Accountant"),
                    ("STAFF", "Staff"),
                ],
                default="STAFF",
                max_length=10,
            ),
        ),
    ]
