# Generated by Django 5.2.11 on 2026-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_aiquerylog_channel_channelmember_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="type",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("PRIVATE", "Private"),
                    ("DIRECT", "Direct"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
    ]
