# Generated by Django 5.2.11 on 2026-03-09 13:35

from django.db import migrations, models


def map_legacy_roles(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.exclude(role='ADMIN').update(role='USER')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_channel_type'),
    ]

    operations = [
        migrations.RunPython(map_legacy_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('ADMIN', 'Administration (Superadmin)'), ('USER', 'User')],
                default='USER',
                max_length=10,
            ),
        ),
    ]
