# Generated by Django 5.2.11 on 2026-03-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmember",
            name="last_typing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="api.message",
            ),
        ),
    ]
