# Generated by Django 5.2.11 on 2026-03-13 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_channelmember_last_typing_at_message_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ManyToManyField(
                blank=True, related_name="deleted_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
