# Generated by Django 5.2.11 on 2026-03-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full Time"),
                    ("PART_TIME", "Part Time"),
                    ("CONTRACT", "Contract"),
                ],
                default="FULL_TIME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("SCREENING", "Screening"),
                    ("TECHNICAL", "Technical"),
                    ("INTERVIEW", "Interview"),
                    ("OFFER", "Offer"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPLIED",
                max_length=20,
            ),
        ),
    ]
